.read data.sql


CREATE TABLE number_of_options AS
  SELECT "REPLACE THIS LINE WITH YOUR SOLUTION";


CREATE TABLE calories AS
  SELECT "REPLACE THIS LINE WITH YOUR SOLUTION";


CREATE TABLE healthiest_meats AS
  SELECT "REPLACE THIS LINE WITH YOUR SOLUTION";

